### ISSUE TITLE
Does not work waste of time

### ISSUE THREAD

**Issue by michalss** [CodeMinion/Another-TV-Remote#4]
does not work total waste of time..

At least add some complete working project example...

`e: D:\Private\Projects\Flutter\android\app\src\main\kotlin\com\example\MainActivity.kt: (9, 9): Unresolved reference: TvRemoteEventProcessor
e: D:\Private\Projects\Flutter\android\app\src\main\kotlin\com\example\\MainActivity.kt: (14, 9): Unresolved reference: TvRemoteEventProcessor
e: D:\Private\Projects\Flutter\android\app\src\main\kotlin\com\example\MainActivity.kt: (30, 13): Unresolved reference: TvRemoteEventProcessor

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
`

**Comment by CodeMinion** [comment]
Hi @michalss ,

Thanks for reaching out about this. I have not had a chance to update the ReadMe but you may find instruction on how to set things up on it's CodeLab https://codelabs.rouninlabs.com/codelabs/another_tv_remote-codelab/index.html?index=..%2F..index#4

Here is also an app that uses it for reference https://github.com/CodeMinion/Flutter-TV

Don't hesitate to reach out if there is anything else I can help with,

**Comment by michalss** [comment]
> 

i allready try this but your are missing one reference from file. So your codelab is wrong and example is not working.. i fixes that but it took me a lot of time..

that other example is also not working, could not build it. Had to make a new project and copy all data from it to a new one.. Then it starts working..
